import type { Metadata } from "next";
import { MarketingNav } from "@/components/marketing-nav";
import { MarketingFooter } from "@/components/marketing-footer";

export const metadata: Metadata = {
  title: "AI Features Disclaimer",
  description:
    "Important information about how Agent Runway's AI features work, what they do not provide, and your responsibilities when using them.",
  robots: { index: false, follow: false },
};

const LAST_UPDATED = "April 6, 2026";

/* -------------------------------------------------------------------------- */

export default function AiDisclaimerPage() {
  return (
    <div className="flex min-h-screen flex-col bg-slate-950">
      <MarketingNav />

      <main className="flex-1 px-6 py-16 sm:px-10">
        <div className="mx-auto max-w-3xl">
          {/* Header */}
          <div className="mb-12">
            <h1 className="text-4xl font-bold tracking-tight text-white">
              AI Features Disclaimer
            </h1>
            <p className="mt-3 text-sm text-slate-500">
              Last updated: {LAST_UPDATED}
            </p>

            {/* Top-level amber warning box */}
            <div className="mt-6 rounded-xl border border-amber-500/40 bg-amber-500/8 p-5">
              <p className="text-base font-semibold leading-relaxed text-amber-300">
                IMPORTANT: Agent Runway&apos;s AI features are informational
                tools only. They do not provide professional advice of any kind.
                Read this page carefully before using any AI feature.
              </p>
            </div>

            <p className="mt-5 text-base leading-relaxed text-slate-400">
              This disclaimer applies to all AI-powered features in Agent
              Runway, including the Flight Crew, AI-generated insights, AI-drafted
              communications, and any other feature that uses artificial
              intelligence or large language model technology to generate text,
              suggestions, or recommendations.
            </p>
          </div>

          {/* Disclaimer content */}
          <div className="space-y-10 text-slate-300">

            {/* ─── 1 ─── */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                1. What the Flight Crew Does
              </h2>
              <p className="leading-relaxed">
                The Flight Crew analyzes the business data you enter into Agent
                Runway &mdash; including GCI income, pipeline deals, expenses,
                goals, and market data &mdash; and generates text-based
                insights, suggestions, and recommendations to help you
                understand your business performance.
              </p>
              <p className="mt-3 leading-relaxed">
                The Flight Crew is a{" "}
                <strong className="text-slate-200">
                  pattern-recognition and language generation tool
                </strong>
                . It does not have judgment, professional qualifications, or
                access to information beyond what you provide. It does not know
                your full financial situation, your brokerage agreement, your
                tax history, your local market conditions, or the personal
                circumstances of you or your clients.
              </p>
            </section>

            {/* ─── 2 ─── */}
            <section className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-6">
              <h2 className="mb-5 text-xl font-semibold text-amber-400">
                2. What the Flight Crew Does NOT Do
              </h2>
              <div className="space-y-5 leading-relaxed text-amber-200/80">

                <div>
                  <h3 className="mb-1 font-semibold text-amber-300">
                    NOT Financial Advice
                  </h3>
                  <p>
                    Nothing generated by the Flight Crew constitutes investment
                    advice, securities advice, or financial planning advice.
                    Agent Runway is not registered as a financial advisor,
                    investment dealer, or portfolio manager under any provincial
                    securities legislation. Do not use AI outputs to make
                    investment or financial planning decisions.
                  </p>
                </div>

                <div>
                  <h3 className="mb-1 font-semibold text-amber-300">
                    NOT Tax Advice
                  </h3>
                  <p>
                    Tax estimates, tax rate displays, and tax-related
                    suggestions generated by the AI are{" "}
                    <strong className="text-amber-300">
                      mathematical approximations only
                    </strong>
                    . They are not professional tax advice. They are not
                    CRA-compliant calculations and have not been reviewed by a
                    tax professional. Always consult a licensed accountant or
                    CPA before making any tax-related decision, filing a tax
                    return, or remitting amounts to the CRA.
                  </p>
                </div>

                <div>
                  <h3 className="mb-1 font-semibold text-amber-300">
                    NOT Accounting Advice
                  </h3>
                  <p>
                    Expense tracking and financial reporting features are
                    organizational tools to help you manage your own records.
                    They are not audited financial statements and do not
                    constitute professional accounting services. Agent Runway is
                    not a licensed accounting firm.
                  </p>
                </div>

                <div>
                  <h3 className="mb-1 font-semibold text-amber-300">
                    NOT Real Estate Brokerage Advice
                  </h3>
                  <p>
                    Pipeline forecasting, client management suggestions, and
                    market data displays are not substitutes for guidance from
                    your broker, manager, real estate board, or local market
                    experts. Agent Runway does not provide real estate brokerage
                    services.
                  </p>
                </div>

                <div>
                  <h3 className="mb-1 font-semibold text-amber-300">
                    NOT Legal Advice
                  </h3>
                  <p>
                    Nothing generated by the AI constitutes legal advice. Do
                    not use AI outputs for contract interpretation, compliance
                    decisions, disputes, or any legal matter. Consult a licensed
                    lawyer for all legal questions.
                  </p>
                </div>

                <div>
                  <h3 className="mb-1 font-semibold text-amber-300">
                    NOT a Substitute for Human Judgment
                  </h3>
                  <p>
                    The AI does not know your full financial situation, your
                    clients, your brokerage agreement, your tax history, or your
                    personal circumstances. You do. No AI output should replace
                    your professional judgment, your advisors&apos; guidance, or
                    your own informed decision-making.
                  </p>
                </div>

              </div>
            </section>

            {/* ─── 3 ─── */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                3. How the AI Works
              </h2>
              <p className="mb-4 leading-relaxed">
                We believe you should understand how the AI technology behind
                Agent Runway&apos;s features actually works:
              </p>
              <ul className="space-y-3 leading-relaxed text-slate-400">
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    AI features are primarily powered by{" "}
                    <strong className="text-slate-300">Anthropic, PBC</strong>{" "}
                    (the Claude family of large language models), with{" "}
                    <strong className="text-slate-300">Groq, Inc.</strong> used
                    as a fallback inference provider and for voice
                    transcription. Both are US-based AI providers using large
                    language model (LLM) technology.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    When you use an AI feature, the relevant business data from
                    your Agent Runway account is{" "}
                    <strong className="text-slate-300">
                      transmitted to Anthropic&apos;s (or, as fallback, Groq&apos;s) servers in the United States
                    </strong>{" "}
                    for processing. The provider processes your query and
                    returns a generated response. Anthropic operates under a
                    zero-retention policy for API traffic by default and does
                    not use customer data to train its models; Groq commits to
                    not retaining or training on customer data.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    No human at Anthropic, Groq, or Agent Runway reads your data
                    as part of normal AI processing. The process is automated.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    AI outputs are{" "}
                    <strong className="text-slate-300">
                      generated probabilistically
                    </strong>
                    . The same input may produce different outputs at different
                    times. This is a fundamental property of large language
                    models, not a bug.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    Agent Runway does{" "}
                    <strong className="text-slate-300">not</strong> verify,
                    fact-check, or certify any AI output before it is shown to
                    you. Outputs are presented as generated.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    AI models can be wrong, outdated, or produce outputs that
                    are inapplicable to your specific circumstances. You should
                    treat all AI outputs as a starting point for your own
                    thinking, not a final answer.
                  </span>
                </li>
              </ul>
            </section>

            {/* ─── 4 ─── */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                4. Your Responsibilities When Using AI Features
              </h2>
              <p className="mb-4 leading-relaxed">
                By using any AI feature in Agent Runway, you agree to the
                following:
              </p>
              <ul className="space-y-3 leading-relaxed text-slate-400">
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    Review every AI output{" "}
                    <strong className="text-slate-300">critically</strong>{" "}
                    before acting on it. Do not treat AI outputs as
                    authoritative or definitive.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    Do not use AI outputs for tax filings, loan applications,
                    mortgage applications, or any official, regulatory, or
                    legally binding documents or processes.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    Do not present AI outputs to your clients as professional
                    recommendations, market analyses, or expert advice.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    Do not use AI-drafted communications (emails, messages, or
                    other content) without your own thorough review and editing
                    before sending. You are responsible for any communication
                    sent under your name.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-1 shrink-0 text-slate-500">&bull;</span>
                  <span>
                    Consult qualified professionals &mdash; accountants, tax
                    advisors, financial planners, real estate brokers, and
                    lawyers &mdash; for all material financial, tax, legal, and
                    business decisions.
                  </span>
                </li>
              </ul>
            </section>

            {/* ─── 5 ─── */}
            <section className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-6">
              <h2 className="mb-4 text-xl font-semibold text-amber-400">
                5. Limitation of Liability for AI Features
              </h2>
              <div className="space-y-4 leading-relaxed text-amber-200/80">
                <p>
                  <strong className="text-amber-300">
                    Agent Runway expressly disclaims all liability for any
                    loss, damage, cost, or consequence of any kind arising from
                    your use of or reliance on AI-generated content.
                  </strong>{" "}
                  This includes, without limitation, any financial loss, tax
                  liability, regulatory penalty, missed transaction, reputational
                  harm, or any other outcome resulting from a decision made based
                  on AI outputs.
                </p>
                <p>
                  By using AI features, you accept full responsibility for all
                  decisions made based on AI outputs. Agent Runway&apos;s role
                  is to provide you with a tool &mdash; what you do with that
                  tool is your responsibility.
                </p>
                <p>
                  See our{" "}
                  <a
                    href="/terms"
                    className="text-amber-400 underline hover:text-amber-300"
                  >
                    Terms of Service, Section 24
                  </a>{" "}
                  for the full limitation of liability and disclaimer of
                  warranties that applies to the Service, including AI features.
                </p>
              </div>
            </section>

            {/* ─── 6 ─── */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                6. AI-Assisted Development
              </h2>
              <p className="leading-relaxed">
                Agent Runway is built with the assistance of AI development
                tools, including Anthropic&apos;s Claude. These tools assist
                with code generation, architecture, and development workflows.
                They are not part of the live platform and do not have access
                to user accounts, data, or any information entered into Agent
                Runway. As a matter of internal policy, user data is never
                provided to development tools.
              </p>
            </section>

            {/* ─── 7 ─── */}
            <section>
              <h2 className="mb-4 text-xl font-semibold text-white">
                7. Contact
              </h2>
              <p className="leading-relaxed">
                If you have questions about our AI features or this disclaimer,
                please contact us at{" "}
                <a
                  href="mailto:hello@agentrunway.ca"
                  className="text-blue-400 hover:text-blue-300"
                >
                  hello@agentrunway.ca
                </a>
                .
              </p>
            </section>

          </div>
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}
