//1000000 = 0.001
//300000 = 0.0003
export const JITO_FEE = 300000
export const COMMITMENT_LEVEL = 'confirmed'
export const BLOCKENGINE_URL = 'tokyo.mainnet.block-engine.jito.wtf'
export const CHECK_FILTER = true
export const CHECK_SOCIAL = true
export const CHECK_NAMEWHITELIST = false
export const CHECK_NAMEBLACKLIST = false
export const CHECK_WALLETWHITELIST = false
export const CHECK_WALLETBLACKLIST = false
export const CHECK_SOLDBALANCE = true
export const USE_SNIPE_LIST = false
export const JITO_MODE = true
export const JITO_ALL = false
export const stop_loss = -0.1
