import { HttpClient } from '../utils/http.js';
import { getCredentials } from '../utils/config.js';

export class AiService {
    constructor() { }

    async generate(prompt: string): Promise<string> {
        const { aiKey, aiProvider, enableAi } = getCredentials();

        if (!enableAi) {
            throw new Error('AI features are disabled. Run "jira config ai enable" to enable.');
        }

        if (!aiKey) {
            throw new Error('AI API Key not configured. Run "jira config ai enable" or "jira config setup".');
        }

        const provider = aiProvider || 'openai';

        switch (provider) {
            case 'openai':
                return this.callOpenAI(aiKey, prompt);
            case 'gemini':
                return this.callGemini(aiKey, prompt);
            case 'anthropic':
                return this.callAnthropic(aiKey, prompt);
            default:
                throw new Error(`Unsupported AI Provider: ${provider}. Supported: openai, gemini, anthropic`);
        }
    }

    async reviewCode(diff: string, context: string): Promise<string> {
        const prompt = `Review the following code changes against the issue context.
Issue Context: ${context}

Code Diff:
\`\`\`diff
${diff.substring(0, 10000)}
\`\`\`
(Diff truncated to 10k chars if longer)

Provide a concise code review. Focus on:
1. Does it meet the issue requirements?
2. Potential bugs or security issues.
3. Code quality improvements.
4. Verify if tests are included if applicable.`;
        return this.generate(prompt);
    }

    async breakdownEpic(summary: string, description: string): Promise<any> {
        const prompt = `Break down the following Epic into child Stories and Tasks.
Epic Summary: ${summary}
Epic Description: ${description || 'N/A'}

Return ONLY a valid JSON array of objects with "type" (Story, Task, Bug), "summary", and "description" fields.
Example: [{"type": "Story", "summary": "...", "description": "..."}]`;
        const response = await this.generate(prompt);
        // Clean markdown code blocks if present
        const jsonStr = response.replace(/```json/g, '').replace(/```/g, '').trim();
        return JSON.parse(jsonStr);
    }

    async generateStandup(yesterday: string, today: string): Promise<string> {
        const prompt = `Generate a daily standup update based on my Jira activity.
Activity (Last 24h):
${yesterday}

Current Assignments (Today):
${today}

Format:
*   **Yesterday**: (Completed items, progress made)
*   **Today**: (Plan for today based on assignments)
*   **Blockers**: (Identify potential blockers or ask if any)

Keep it concise and professional.`;
        return this.generate(prompt);
    }

    async generateJql(query: string): Promise<string> {
        const prompt = `Convert the following natural language query into Jira JQL.
Query: "${query}"

Return ONLY the raw JQL string. No markdown, no explanations.
Today is ${new Date().toISOString().split('T')[0]}.`;
        const response = await this.generate(prompt);
        return response.replace(/```/g, '').trim();
    }

    async callOpenAI(key: string, prompt: string): Promise<string> {
        try {
            const client = new HttpClient();
            const response = await client.post('https://api.openai.com/v1/chat/completions', {
                model: 'gpt-4o',
                messages: [{ role: 'user', content: prompt }],
                temperature: 0.7
            }, {
                headers: { 'Authorization': `Bearer ${key}` }
            });
            return response.data.choices[0].message.content;
        } catch (e: any) {
            throw new Error(`OpenAI API Error: ${e.response?.data?.error?.message || e.message}`);
        }
    }

    async callGemini(key: string, prompt: string): Promise<string> {
        try {
            // Gemini REST API — uses generativelanguage.googleapis.com
            const model = 'gemini-2.0-flash';
            const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`;
            const client = new HttpClient();

            const response = await client.post(url, {
                contents: [{
                    parts: [{ text: prompt }]
                }],
                generationConfig: {
                    temperature: 0.7,
                    maxOutputTokens: 2048
                }
            }, {
                headers: { 'Content-Type': 'application/json' }
            });

            const candidates = response.data.candidates;
            if (!candidates || candidates.length === 0) {
                throw new Error('No response generated by Gemini.');
            }

            return candidates[0].content.parts.map((p: any) => p.text).join('');
        } catch (e: any) {
            if (e.response?.data?.error) {
                throw new Error(`Gemini API Error: ${e.response.data.error.message}`);
            }
            throw new Error(`Gemini API Error: ${e.message}`);
        }
    }

    async callAnthropic(key: string, prompt: string): Promise<string> {
        try {
            // Anthropic Messages API
            const client = new HttpClient();
            const response = await client.post('https://api.anthropic.com/v1/messages', {
                model: 'claude-sonnet-4-20250514',
                max_tokens: 2048,
                messages: [{ role: 'user', content: prompt }]
            }, {
                headers: {
                    'x-api-key': key,
                    'anthropic-version': '2023-06-01',
                    'Content-Type': 'application/json'
                }
            });

            return response.data.content
                .filter((block: any) => block.type === 'text')
                .map((block: any) => block.text)
                .join('');
        } catch (e: any) {
            if (e.response?.data?.error) {
                throw new Error(`Anthropic API Error: ${e.response.data.error.message}`);
            }
            throw new Error(`Anthropic API Error: ${e.message}`);
        }
    }
}

export const aiService = new AiService();
